#CHALLENGE

Find a way to achieve this, with codes we have discussed or codes from other resources. Let's build your ability to problem solve.

Github/StackOverflow/ChatGPT is allowed.

GOALS: <br>
1. Use SuperStore Data.
2. Create an 'Age' Column from the data you have
3. Also create an 'AgeCat' column that has the categories per generation.
Use the labeling age category attached below:
4. Extract at least 3 insights from the data you have.
5. Have at least 1 visualization

*hint:* <br>

For the age, let's say that our data is gathered on the last day of 2015.

**Labeling Age categories**

'Gen Z (0-24)': Ages from 0 to 24 (inclusive)

'Gen Y (25-39)': Ages from 25 to 39 (inclusive)

'Gen X (40-54)': Ages from 40 to 54 (inclusive)

'Older (55-59)': Ages from 55 to 59 (inclusive)

'Senior (60+)': Ages 60 and above

In [28]:
import pandas as pd

# SuperStore data from local CSV file
data = pd.read_csv('/content/SuperStore-Data (2).csv')

# Data is gathered on last day of 2015
data['Age'] = 2015 - data['Year_Birth']

# Define the age categories and labels
bins = [0, 24, 39, 54, 59, data['Age'].max() + 1]
labels = ['Gen Z (0-24)', 'Gen Y (25-39)', 'Gen X (40-54)', 'Older (55-59)', 'Senior (60+)']

data['AgeCat'] = pd.cut(data['Age'], bins=bins, labels=labels, right=True, include_lowest=True)

display(data[['Year_Birth', 'Age', 'AgeCat']].head())
display(data['AgeCat'].value_counts().sort_index())

# Calculate Total Spending by summing relevant columns
data['TotalSpending'] = data['MntWines'] + data['MntFruits'] + data['MntMeatProducts'] + \
                        data['MntFishProducts'] + data['MntSweetProducts'] + data['MntGoldProds']

# Insight 1: Average Income by Age Category
print("\nInsight 1: Average Income by Age Category:")
display(data.groupby('AgeCat', observed=False)['Income'].mean().sort_index().round(2))

# Insight 2: Average Total Spending by Age Category
print("\nInsight 2: Average Total Spending by Age Category:")
display(data.groupby('AgeCat', observed=False)['TotalSpending'].mean().sort_index().round(2))

# Insight 3: Education Level Distribution by Age Category
print("\nInsight 3: Education Level Distribution by Age Category:")
education_distribution = data.groupby('AgeCat', observed=False)['Education'].value_counts(normalize=True).mul(100).rename('percentage').reset_index()
display(education_distribution)

   Year_Birth  Age         AgeCat
0        1970   45  Gen X (40-54)
1        1961   54  Gen X (40-54)
2        1958   57  Older (55-59)
3        1967   48  Gen X (40-54)
4        1989   26  Gen Y (25-39)

AgeCat
Gen Z (0-24)      43
Gen Y (25-39)    652
Gen X (40-54)    924
Older (55-59)    251
Senior (60+)     368
Name: count, dtype: int64

Insight 1: Average Income by Age Category:

AgeCat
Gen Z (0-24)     57882.56
Gen Y (25-39)    47245.19
Gen X (40-54)    51854.57
Older (55-59)    56207.91
Senior (60+)     58778.22
Name: Income, dtype: float64

Insight 2: Average Total Spending by Age Category:

AgeCat
Gen Z (0-24)     927.19
Gen Y (25-39)    515.52
Gen X (40-54)    582.96
Older (55-59)    671.28
Senior (60+)     741.86
Name: TotalSpending, dtype: float64

Insight 3: Education Level Distribution by Age Category:

           AgeCat   Education  percentage
0    Gen Z (0-24)  Graduation   55.813953
1    Gen Z (0-24)    2n Cycle   13.953488
2    Gen Z (0-24)       Basic   13.953488
3    Gen Z (0-24)      Master    9.302326
4    Gen Z (0-24)         PhD    6.976744
5   Gen Y (25-39)  Graduation   54.447853
6   Gen Y (25-39)         PhD   14.723926
7   Gen Y (25-39)    2n Cycle   13.190184
8   Gen Y (25-39)      Master   13.190184
9   Gen Y (25-39)       Basic    4.447853
10  Gen X (40-54)  Graduation   49.242424
11  Gen X (40-54)         PhD   24.783550
12  Gen X (40-54)      Master   17.099567
13  Gen X (40-54)    2n Cycle    7.359307
14  Gen X (40-54)       Basic    1.515152
15  Older (55-59)  Graduation   49.800797
16  Older (55-59)      Master   20.318725
17  Older (55-59)         PhD   19.521912
18  Older (55-59)    2n Cycle    9.561753
19  Older (55-59)       Basic    0.796813
20   Senior (60+)  Graduation   45.652174
21   Senior (60+)         PhD   29.076087
22   Senior (60+)      Master   19.293478
23   Senior (60+)    2n Cycle    5.163043
24   Senior (60+)       Basic    0.815217