PART 1:

For this part of the practical session, you would have to achieve the goals listed below. In the end, everyone will present about the nature of their data, the steps they did, explain the purpose of that step, and share some discoveries if you encounter any. Basically, play and explore with the codes and the data to get the hang of the analytics tools discussed.

Main Goal: Be able to read a file and create a dataframe.

1.	Grab your own dataset from the internet (I highly recommend Kaggle)
2.	Observe your own dataset
3.	Apply some of the functions you learned this week.
4.	Get some insights from the dataset (examples: mean, median, mode, null values, etc.)
5.	Document your processes and outputs.
6.	Take notes of the functions you are having troubles with.k

In [44]:
import pandas as pd

# Importing data from Kaggle
Data = 'Video_Games_Sales_as_at_22_Dec_2016.csv'

# Read CSV file in DataFrame
df = pd.read_csv(Data)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object
 4   Publisher        16665 non-null  object
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       10015 non-null  object
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  object
 15  Rating           9950 non-null   object
dtypes: float64(9), object(7)
memory usage: 2.0+ MB

In [24]:
display(df.head())

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
missing_values = df.isnull().sum()
display(missing_values)

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         6704
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

In [26]:
# Clean data
df['Publisher'] = df['Publisher'].fillna('Unknown')

# Change missing 'Year_of_Release' values to the median
df['Year_of_Release'] = df['Year_of_Release'].fillna(df['Year_of_Release'].median())
df['Year_of_Release'] = df['Year_of_Release'].astype(int)

# Drop columns with high number of missing values
columns_to_drop = ['Critic_Score', 'Critic_Count', 'User_Score', 'User_Count', 'Developer', 'Rating']
df.drop(columns_to_drop, axis=1, inplace=True, errors='ignore')

missing_values = df.isnull().sum()
display(missing_values)

df.info()

Name               2
Platform           0
Year_of_Release    0
Genre              2
Publisher          0
NA_Sales           0
EU_Sales           0
JP_Sales           0
Other_Sales        0
Global_Sales       0
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16719 non-null  int64
 3   Genre            16717 non-null  object
 4   Publisher        16719 non-null  object
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
dtypes: float64(5), int64(1), object(4)
memory usage: 1.3+ MB

In [27]:
# Drop rows where 'Name' or 'Genre' are missing
df.dropna(subset=['Name', 'Genre'], inplace=True)

missing_values_after_drop = df.isnull().sum()
display(missing_values_after_drop)

df.info()

Name               0
Platform           0
Year_of_Release    0
Genre              0
Publisher          0
NA_Sales           0
EU_Sales           0
JP_Sales           0
Other_Sales        0
Global_Sales       0
dtype: int64

<class 'pandas.core.frame.DataFrame'>
Index: 16717 entries, 0 to 16718
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16717 non-null  object
 2   Year_of_Release  16717 non-null  int64
 3   Genre            16717 non-null  object
 4   Publisher        16717 non-null  object
 5   NA_Sales         16717 non-null  float64
 6   EU_Sales         16717 non-null  float64
 7   JP_Sales         16717 non-null  float64
 8   Other_Sales      16717 non-null  float64
 9   Global_Sales     16717 non-null  float64
dtypes: float64(5), int64(1), object(4)
memory usage: 1.4+ MB

In [32]:
# Insight in top 10 games sold in 2016
top_sales = df.sort_values(by = 'Global_Sales', ascending = False).head(10)
top_sales

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53
1,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,New Super Mario Bros.,DS,2006,Platform,Nintendo,11.28,9.14,6.50,2.88,29.80
7,Wii Play,Wii,2006,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92
8,New Super Mario Bros. Wii,Wii,2009,Platform,Nintendo,14.44,6.94,4.70,2.24,28.32
9,Duck Hunt,NES,1984,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31

In [35]:
# Get mean, median, and mode for all sales columns
sales_columns = ['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']

display(df[sales_columns].mean())

display(df[sales_columns].median())

display(df[sales_columns].mode())

NA_Sales        0.263255
EU_Sales        0.145010
JP_Sales        0.077610
Other_Sales     0.047333
Global_Sales    0.533462
dtype: float64

NA_Sales        0.08
EU_Sales        0.02
JP_Sales        0.00
Other_Sales     0.01
Global_Sales    0.17
dtype: float64

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0       0.0       0.0       0.0          0.0          0.02

In [43]:
# Platform, Genre, and Publisher with most games released
list_columns = ['Platform', 'Genre', 'Publisher']

for col in list_columns:
    print(f"{col}: {df[col].mode().tolist()}")

Platform: ['PS2']
Genre: ['Action']
Publisher: ['Electronic Arts']

6. Take notes of the functions you are having troubles with.k

Issues related to finding solution for so many missing values in review score columns. Decided to remove columns and focus on sales based on Platform, Genre, and Publisher.